name: 'App Shield protect'
description: 'Secure your Android and iOS mobile apps with proven in-app protection including obfuscation, device checks and anti-tamper'
author: 'Verimatrix'
branding:
  icon: upload-cloud
  color: purple
inputs:
  api-key-id:
    description: 'API Key ID'
    required: true
  api-key-secret:
    description: 'API Key Secret'
    required: true
  app-file:
    description: 'Mobile application file'
    required: true

outputs:
  protected-file:
    description: 'Protected application file name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    API_KEY_ID: ${{ inputs.api-key-id }}
    API_SECRET: ${{ inputs.api-key-secret }}
    APP_FILE: ${{ inputs.app-file }}
